### PR TITLE
Version 1.0

### LINKED ISSUE #17: ES6: move encrypt/decrypt methods to root object
For import friendliness, move the important methods to the root object so the following is possible:

```javascript
import { encryptWithPassword } from "iocane";
```

### LINKED ISSUE #25: Async encryption/decryption
The encryption happens synchronously which blocks the event loop meaning the browser/node process hangs and can't do anything else until encryption has finished.

It would be much better if encryption/decryption happened asynchronously. Any plans to support this? Would you accept a PR?

### LINKED ISSUE #26: Implement GCM
https://gist.github.com/chris-rock/fe87dd35d6168512a2f7

### LINKED ISSUE #27: Why are a random amount of PBKDF2 rounds used?
A random number between `derivedKeyIterationsMin` and `derivedKeyIterationsMax` is chosen. Why is this?

https://github.com/perry-mitchell/iocane/blob/91f37af4e6e62dedf51fedc03362c8c601ca2fdb/source/derive.js#L15-L20

Is it so if a user re-uses a password they still have a unique key?

If so, why is this beneficial? If someone successfully brute forced a key they would have generated the source password text in the process. They could regenerate the other keys by running the password through PBKDF2 the required amount of rounds.

### PR DESCRIPTION
**Pull request by perry-mitchell**
Rebuild of **iocane** from the ground up. New API will be much easier to use, and will feature AES-GCM support.

Closes #27 (random derivation rounds)
Closes #26 (GCM)
Closes #25 (async encryption)
Closes #17

### CODE REVIEW

**Comment by lukechilds** [comment]
@perry-mitchell What are the benefits of GCM over CBC + HMAC?

Although I've read mostly positive things online, there are some disadvantages to be aware of:

https://crypto.stackexchange.com/questions/18420/aes-gcm-disadvantage

I'm by no means saying I don't think you should support GCM, just interested in the reasoning.

**Comment by perry-mitchell** [comment]
@lukechilds I've been criticised quite a bit already using CBC mode instead of GCM when building Buttercup, and I've read a lot on why CBC mode is generally regarded as less secure than GCM. I know that they're not directly comparable for every use case, but I've simply just read more on that GCM would be more suitable from a security standpoint for encrypting static blocks of text. [Articles I've found](https://crypto.stackexchange.com/questions/10775/practical-disadvantages-of-gcm-mode-encryption/10808#10808) on direct comparison do indicate the same, but mostly due to the fact that GCM is more easily implemented.

We're considering moving to GCM for Buttercup, as it should be more than suitable, but **iocane** sits in the middle and can more easily support both CBC and GCM operation modes.

I took this away from the article I linked:

> GCM is very good mode of operation, and it often is more convenient than legacy algorithms combinations like CBC + HMAC. However, it is not universal solution (none of the modes is)

All the discussion I read is definitely mixed. As I'm not pretending to be an expert on encryption, I'm heading in the direction that _seems_ to be the safest bet in terms of security and me not screwing the implementation up 😅.

**Comment by perry-mitchell** [comment]
Hmm.. still need to figure out how to use associated data for the auth tag with GCM. This was a nice bonus when using HMAC for CBC, but it seems to be missing in GCM examples I've seen.

EDIT: Nevermind, [got it](https://github.com/perry-mitchell/iocane/pull/28/files#diff-ffd1d61261af7bd32b247ca0426b3fa7R118).

**Comment by lukechilds** [comment]
I'm not sure Buttercup is a good candidate for GCM. In GCM mode key/IV pair reuse is absolutely catastrophic.

From the article you linked:

>Generally, GCM is most convenient for uses where new keys are agreed or transported as a part of the protocol (TLS or IPsec). If there is use where a persistently stored key is needed, then it can be cumbersome to ensure IV uniqueness.

Buttercup obviously needs a persistent key because the users password doesn't change. You are also using random IV generation which is not recommended for GCM mode. The IV should be a nonce, if you're using the same key you should have some sort of counter method or something to ensure the iv is unique and not re-used.

If an attacker can find multiple messages encrypted with the same key/IV they can deduce the original contents of the message.

So using this GMC implementation in Buttercup with cloud sync combines:
- Key reuse
- Potential IV reuse
- Cloud providers like DropBox storing incremental backups

With those three scenarios combined, if an attacker (or rogue employee) gains access to my DropBox account, they have a history of multiple backup files. If any of those historic backups randomly generated the same IV they can deduce the contents of my entire password store.

I'm aware that generating the same IV isn't that likely, but it's possible and makes me feel pretty uneasy. This wouldn't be an issue with CBC mode which is why I think GCM is not suitable for Buttercup.

**Comment by perry-mitchell** [comment]
That's a good point @lukechilds - I'll try to spend more time looking in to GCM implementation to verify everything. GCM would be highly beneficial for Buttercup in many ways - execution speed, cross-platform implementation is easier, less error prone (assuming the nonce situation is not a problem). That being said, I won't obviously put it in to use if there are doubts on it.

This is disappointing however from the standpoint that there is still a major crypto bug on the mobile app. Certain payloads can't be decrypted due to failing HMAC authentication.. this would've certainly solved that.

The nonce could be incremented with each encryption of course - what's your opinion on that? I guess it could still be risky if 2 encryptions are performed at the same time using coincidentally the same nonce.

**Comment by perry-mitchell** [comment]
Starting to wonder if using GCM is still a non issue - the key shouldn't be repeated due to the [salt being randomly generated each time](https://github.com/perry-mitchell/iocane/blob/master/source/derivation.js#L39). That, and if we'd left the random iteration rounds, we'd have a very random key. If we encrypted the same content with the same key over and over right now, it should be expected to be highly improbable that we'd ever see the same key. Couple that with the entropy added by using random derivation rounds, and that would drastically increase. When you put that beside the random IV iocane uses, the entropy increases again.

At this point I don't see any possibility of key+iv duplicate generations for iocane's GCM encryption.

**Comment by lukechilds** [comment]
Salted keys are a good point, I totally overlooked that. As long as the salt used to derive the key is sufficiently random it should fine.

As discussed in https://github.com/perry-mitchell/iocane/issues/27 though, we shouldn't use random amounts of PBKDF2 rounds to increase randomness of the key. That's the salts job. Fixed number of rounds + salt with a random IV will be fine.

**Comment by perry-mitchell** [comment]
Sounds good to me 👍

**Pull request merged**
